export const personalidade: string[] = [
    'Mentiroso(a)',
    'Mandão/Mandona',
    'Teimoso(a)',
    'Medroso(a)',
    'Brigão/Brigona',
    'Maria vai com as outras',
    'Subserviente',
    'Intrometido(a)',
    'Calado(a)',
    'Explosivo(a)',
    'Destemido(a)',
    'Falador(a)',
    'Caladão',
    'Curioso(a)',
    'Burro(a)',
    'Arrogante',
    'Pessimista',
    'Otimista',
    'Ingênuo(a)',
    'Temeroso(a)',
    'Temerário(a)',
    'Cordial',
    'Grudento(a)',
    'Confiante',
    'Rude',
    'Delicado(a)',
    'Grosseiro(a)',
    'Polido(a)',
    'Desengonçado(a)',
    'Pacato(a)'
];

export const humor: string[] = [
'Irritado(a)',
'Desconfiado(a)',
'Hostil',
'Chateado(a)',
'Deprimido(a)',
'Tenso(a)',
'Feliz',
'Sorridente',
'Relaxado(a)',
'Desligado(a)',
'Ostentador(a)',
'Eufórico(a)',
'Ansioso(a)',
'Expansivo(a)',
'Introvertido(a)',
'Desagradável'
];

export const fisico: string[] = [
    'Gordo(a)',
    'Franzino(a)',
    'Atlético(a)',
    'Alto(a)',
    'Baixinho(a)',
    'Esguio',
    'Gigante',
    'Careca',
    'Cabeleira desgrenhada',
    'Cabelo bem penteadinho',
    'Esquelético(a)',
    'Ombros largos',
    'Cabelo Ensebado',
    'Braços fortes',
    'Cabelos Grisalhos',
    'Anca Larga',
    'Cabelos Claros',
    'Cabelos Escuros',
    'Cabelo bem curto',
];

export const fisico2: string[] = [
    'Barbudo',
    'Orelhudo',
    'Narigudo',
    'Olhos esbugalhados',
    'Vesgo',
    'Tem uma cicatriz no rosto',
    'Tem um dente quebrado',
    'Bigode',
    'Suado(a)',
    'Olhos Verdes',
    'Olhos Azuis',
    'Olhos Negros',
    'Cicatriz na bochecha',
    'Cicatriz no olho',
    'Pedaço da orelha faltando',
    'Dentes em perfeito estado',
    'Nariz torto',
];

export const peculiaridade: string[] = [
  'Conhece os negócios escusos de uma cidade longínqua',
  'Usa uma capa vermelha',
  'Tem um dente faltando',
  'As roupas estão sujas',
  'Olhar sombrio',
  'Parece doente',
  'Usa um tapa olho',
  'Não tem um dedinho',
  'Tem mancha de nascimento',
  'Tem um olho de vidro',
  'Não para de coçar os olhos',
  'Fala espremendo os olhos',
  'Tem um bafo horrível',
  'Está cheirando a álcool',
  'Está cheirando a fezes',
  'Suas botas estão furadas',
  'Sua roupa está manchada de sangue',
  'Está sempre tossindo',
  'Tem uma voz rouca',
  'Parece pálido',
  'Tem manchas de sangue pelas roupas',
  'Suas mãos são bastante sujas',
  'Anda de maneira engraçada',
  'Tem algumas cicatrizes pelo corpo',
  'Usa um belo chapéu',
  'Feio de doer',
  'Suas bochechas são grandes',
  'Testa enorme, dá para bater um bife',
  'Diz para todos que é abençoado por um Deus local',
  'Tem trajes bem cortados, dignos de um nobre',
  'Usa uma capa vermelha',
  'Ligeiramente atraente',
  'Trabalhou numa taverna',
  'Conhece um latoeiro'
];